#define DR_WAV_IMPLEMENTATION
#include <dr_wav.h>
#define MINIMP3_IMPLEMENTATION
#define MINIMP3_ONLY_MP3
#include <minimp3.h>
#include <minimp3_ex.h>
#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>
#include "pch.h"